# Você pode usar números inteiros também, esse número com decimais é apenas para exemplificar o uso.
money_format:
  # K, M, B...
  use_suffix: true
  #
  # 0 = 1K, 2K
  # 1 = 1.1K, 2.1K
  # 2 = 1.15K, 2.15K
  #
  # Sugiro que não passe de duas, além de ficar esteticamente feio, pode ocorrer um erro na formatação.
  #
  casas_decimais: 0
  # formato usado caso use_suffix esteja como false
  format: 0,000.00

# Configure apenas se tiver ativado o use_suffix
suffixes:
  - 'K'
  - 'M'
  - 'B'
  - 'T'
  - 'Q'
  - 'QQ'
  - 'Sx'
  - 'Sp'
  - 'Oc'
  - 'D'
  - 'Un'

valor_minimo: 1000.0

# Mensagens enviadas:
#
# @min_value = valor mínimo (variável geral)
# @sender = quem enviou o comando (variável local)
# @procurado = quem está sendo procurado (variável local)
# @valor = valor enviado / valor pela cabeça (variável local)
# @killer = quem matou (variável local)
#
# Dicionário:
#
#  * variáveis gerais funcionam em todas as mensagens.
#  * variáveis locais funcionam em mensagens específicas (já têm a variável como padrão)

mensagens:
  nao_e_um_jogador: '&cVocê deve ser um jogador para executar esse comando.'
  numero_invalido: '&cO número inserido é inválido.'
  jogador_offline: '&cO jogador está off-line.'
  numero_menor_ou_igual_a_zero: '&cO número não pode ser menor ou igual a zero.'
  quantia_insuficiente: '&cO valor inserido não é maior que o valor mínimo (@min_value)'
  player_sendo_procurado: '&c[Procurado] &7O jogador &e@procurado &7está sendo procurado por &e@sender&7, que adicionou &e@valor coins &7à sua cabeça.'
  saldo_insuficiente: '&cVocê não tem dinheiro suficiente.'
  nao_pode_procurar_a_si_mesmo: '&cVocê não pode procurar por si mesmo.'
  procurado_valor: '&fValor: &e@valor coins'
  procurado_morto: '&cO procurado &e@procurado &cfoi morto por &e@killer&c.'